version: "3.9"
services: 
    client_new:
        container_name: client_new
        restart: always
        build: ./client
        ports:
            - "3000:3000"
        links:
            - app_new
    app_new:
        container_name: app_new
        restart: always
        build: ./api
        ports: 
            - "4000:4000"
        depends_on: 
            - mongo_new
    mongo_new :
        container_name: mongo_new
        image: mongo
        restart: always
        expose: 
            - "27017"
        volumes:
            - ./data:/data/db
        ports: 
            - "27017:27017"
 